version: "3.8"

services:
  backend:
    build:
      context: ./oqq_backend
      dockerfile: Dockerfile
    container_name: oqq-backend
    ports:
      - "4000:4000"
    env_file:
      - ./oqq_backend/.env
    volumes:
      - ./oqq_backend/public/images:/app/public/images
    restart: unless-stopped

  frontend:
    build:
      context: ./oqq_frontend
      dockerfile: Dockerfile
    container_name: oqq-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
